name: Build
on:
    push:
      branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t getname .
      - name: Run Docker Image
        run: docker run -d --name mygetname -p 5000:443 getname
      - name: Test GetName Service
        run: curl -k https://localhost:5000/
