name: Build
on:
    push:
      branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t getname .
      - name: Run Docker Image
        run: docker run -d --name mygetname -p 443:443 getname
      - name: Not Test GetName Service
        run: |
            sleep 10
            docker logs mygetname --tail 50
            curl -k https://localhost/ --fail
